HeadpatsStory = Story:extend()

function HeadpatsStory:new()
    HeadpatsStory.super.new(self)
    self.lines = { 
        "#bg gfx/bg1.png",
        "3015.UC",
        "02.14 2300 HOME",
        "#bg gfx/bg7.png",
        "#music bgm/Lazy Marine - 91 T1.wav",
        "A gust of wind howls through my window as the metallic frame of the house reverberates against itself.",
        "I walk over to the window to shut it.",
        "Click.",
        "The bright Capital District lights paint the nearby area, tapering as it enters the Auxiliary District.",
        "Night has fallen and so I sit at the edge of my bed mulling over today's research.",
        "No luck today, huh.",
        "Exasperated, I set my research down and lay flat on my bed with my arms extended out.",
        "It's like I'm waiting for \"it\" to just fall into my arms.",
        "A handwritten schedule I wrote for {girl} catches the corner of my eye.",
        "I sit back up and decide to look over my handiwork.",
        "{girl} has been attending to my preset schedules without fail--",
        "She's certainly good at listening to what she's told.",
        "A very good listener.",
        "But it makes me wonder even more where she came from, why she specifically was sent to me?",
        "...",
        "...",
        "And I also wonder if the Outer Federation really is watching my every move...",
        "...",
        "..I mentally take note of extra precautions to take during my daily shower...",
        "In any case, it's helped me get my mind off of my research from time to time.",
        "She can't possibly function without me giving her direct instruction so it's good I've taken some time to make these.",
        "If I'm--no, we're--to succeed, I'm going to need to take great care in how she grows.",
        "I truly hope she sees that we're not too fargone as a species.",
        "The silence of the room is broken by a creak at my door.",
        "{girl} stands half-way into the doorway, eyes downcast.",
        "#portrait gfx/portrait_baby_{type}.png",
        "I had given {girl} her own room in the house--",
        "I have a sizeable living quarter given to me by the neo-government considering my contributions to society.",
        "It was no problem just giving her a section of the house to live in.",
        "So... why was she here now?",
        "Another gust of wind knocks violently against the house frame.",
        "{girl}: !!!!",
        "Her eyes shut tight as she jumps through the doorframe, now standing completely in my room.",
        "I see clutched in her hand a pillow...currently being asphyxiated by her grip.",
        "Ok, I get it now.",
        "I beckon her closer and put a hand on her shoulder.",
        "Her eyes look up at me, seemingly on the verge of tears.",
        "{player}: \"Look.\"",
        "I motion towards the window.",
        "{player}: \"That's just wind--uhm. Wind is like, the movement of air--\"",
        "She continues to look at me, expectantly.",
        "{player}: \"And, uh, differences in atmospheric pressure cause the air to move from areas of higher pressure to lower pressure.\"",
        "{player}: \"The noise occurs because the movement of air causes friction against the objects it touches.\"",
        "{player}: \"Since our house is made of metal, the friction and reverberation are particularly pronounced--\"",
        "{player}: \"--like the noise that happens when you hit a hollow object.\"",
        "{player}: \"There are other factors that affect wind such as the Coriolis effect and temperature profiles for geographic regions but--\"",
        "{player}: \"--Ok so basically, there's nothing to be scared of. This is just how the world works.\"",
        "I raise a hand and place it on her head.",
        "Pat, pat.",
        "{player}: \"You can head back to your room now--really, there's nothing to worry about!\"",
        "Lifting my hand from her head, she doesn't seem convinced...",
        "But.",
        "She's a good listener.",
        "She turns and slowly shuffles dejectedly out of my room.",
        "Uh.",
        "Did I do that right?",
        "..",
        "I slide myself under my bed covers, my mind replaying what occurred like a broken record.",
        "What if I--no, that's stupid. How about--",
        "Wait, but then--",
        "The decision branch in my head has grown exponentially to consider every possibility.",
        "Surely, that was the best outcome I could have achieved, isn't it?",
        "..",
        "I feel something soft, lie next to me.",
        "..",
        "I turn towards it.",
        "..",
        "It's {girl}.",
        "...and she's already fast asleep.",
        "#bg gfx/bg1.png",
        "..",
        "I hope the Outer Federation gives me points for how I handled this.",
        "That night I got some of the best rest I've ever had."
		,"#music bgm/Lazy Marine - 91 full.wav"
    }
end
