HelpPt1Story = Story:extend()

function HelpPt1Story:new()
    HelpPt1Story.super.new(self)
    self.lines = { 
        "3016.UC",
        "06.20 1730",
        "We're out at the market doing some grocery shopping in the Auxiliary District.",
        "The food out here tends to taste...less sterile.",
        "The price point also being competitive is just another perk which I will choose to gloss over.",
        "As of late, {girl} has been working a variety of jobs and the people in this area seem to have gotten used to seeing her around town.",
        "#portrait gfx/portrait_baby_{type}.png",
        "Watching, {girl} excitedly dart about the market put a smile on my face like none other.",
        "Life in the Auxiliary really is a stark contrast to life in the Capital.",
        "Here, efficiency still reigns but not as a matter of preference.",
        "It was necessary to survive.",
        "The people here formed a wide support net for its people--",
        "--pulling the community forward together, instead of individually.",
        "{player}: \"Come {girl}, let's head over to the fruit stands and finish up for today.\"",
        "{girl} runs to my side and grabs my hand.",
        "However, as we make our way towards the fruit stands we hear see a crowd of people around an apple wagon.",
        "A voice shouts out,",
        "Distant Voice: \"..-can't you see you're ruining business!\"",
        "We make our way to the edge of the crowd to figure out what all the commotion is.",
        "There is a young girl cowering in front of a push cart full of apples.",
        "A man and woman stand before her.",
        "{player}: \"Judging by their dress, they're from the Capital...\"",
        "District Man: \"The presence of your market here is a blight on our industry.\"",
        "District Woman: \"Yes, can't you see your products are inferior--the nutritional yield is far below what we service in the Capital.\"",
        "District Man: \"Well said indeed.\"",
        "The District Man picks up an apple from the cart and bites from it.",
        "His face contorts with frustration and anger as he spits the apple back out onto the road.",
        "He violently grabs the car by the side and tears the supporting wall asunder.",
        "Dozens of apples spill out of the cart onto the road.",
        "I feel {girl}'s grip tighten against my hand.",
        "..",
        "But then, the grip loosens significantly.",
        "Wait.",
        "No.",
        "She's walking towards the cart.",
        "I reach out past the crowd but the density of it pushes me back.",
        "{girl} gets on her hands and knees, picking up the fallen apples.",
        "District Man: \"There will be no need for that child, let them rot in the street.\"",
        "The District Man reaches down to grab her by the shoulder--",
        "--but his hand is swiftly knocked away by her hand.",
        "She continues to pick the apples up.",
        "Turning to the cowering girl, {girl} helps her stand, offering to help fix her apple wagon.",
        "Apple Girl: \"(hic)..(hic)..I-I know they're not the best... b-but I have to help my father somehow...he's sick and--\"",
        "I finally break through the crowd.",
        "District Woman: \"Did you not hear what my husband said?! The insolenc--\"",
        "{girl} gives the District Woman a glare worth fifty daggers.",
        "I step between them.",
        "{player}: \"Alright, that'll be enough.\"",
        "District Man: \"And just who do you think you are?\"",
        "I love this part.",
        "I flash my papers, identifying myself as employed directly by the neo-government.",
        "{player}: \"My contribution.\"",
        "The man's face goes white.",
        "District Man: \"Come dear, we're leaving.\"",
        "They leave just as quickly as they came, like dogs with tails between their legs.",
        "Apple Girl: \"..t-thank you..\"",
        "Looking out at the street, there is still a significant amount of apples still on the floor.",
        "{player}: ...",
        "{player}: \"..guess we have some work to do..\"",
        "{girl}: (nods)",
        "We spent the rest of the evening picking up apples."
    }
end
