BorgarStory = Story:extend()

function BorgarStory:new()
    BorgarStory.super.new(self)
    self.lines = { 
        "3017.UC",
        "08.12 1745",
        "I've received a fair amount of money from work this month due to some progress with my robotics work.",
        "I figure I should use this as an opportunity to treat {girl} to some food.",
        "In the last millenia, there was a particularly common source of protein that was consumed daily.",
        "Apparently, that food was called",
        "\"Hamburgers\".",
        "Interestingly enough, I heard they used to eat three or four of these in one sitting at one point of time in the distant past.",
        "There's only one place around here though that serves this specialty.",
        "..And it's not cheap.",
        "In fact, it's so expensive I've never even bothered going myself.",
        "But today's special.",
        "Oh--",
        "--there she is.",
        "{player}: \"I did some thinking for what we should eat for dinner today and...\"",
        "{girl}'s eyes perk up with a radiant glimmer.",
        "{player}: \"{girl}, let's get hamburgers today.\"",
        "{girl}: \"..ham..burger?\"",
        ".",
        ".",
        ".",
        "At Up-N-Down Burger.",
        "...",
        "We find ourselves next in an extraordinarily long line for the counter.",
        "This place has been here for decades but not sure where the unusual name came from.",
        "Up-N-Down Worker: \"Next!\"",
        "{player}: \"That's us, let's go.\"",
        "{girl}: (nods)",
        "Up-N-Down Worker: \"Welcome to Up-N-Down Burger, home of the Up-N-Down Burger, may I take your order?\"",
        "I whisper into {girl}'s ear--",
        "{player}: \"Check this out--\"",
        "{player}: \"AHEM, yes, I would like two of your finest burger meals.\"",
        "{player}: \"--And let me get the burger, fries and drink\"",
        "{player}: \"MAMMAL STYLE\"",
        "I give a wink to {girl}.",
        "Up-N-Down Worker: \"Sir, you can't get a Mammal Style drink.\"",
        "What..",
        "What??",
        "I did my research on this establishment to order specifically from the secret menu.",
        "...What did I do wrong??",
        "{player}: \"O-oh, fair enough then. Just the others Mammal Style.\"",
        "Up-N-Down Worker: \"Alright, here you go.\"",
        "Wait.",
        "That was fast.",
        "I was expecting expensive food to take a long time.",
        "I guess that explains why people are willing to wait in such a long line.",
        "And so, we sat, idly chatting while eating our hamburgers.",
        "It being a finger food caught me off guard but those concerns were quickly washed away by {girl}.",
        "Across the table from me was {girl} with a radiant smile on her face.",
        "I could tell she was enjoying the food.",
        "Her manners were...uncouth to say the least.",
        "But today's special.",
        "Her elbows rested on the table, her mouth biting into the hamburger with one hand and a fry in the other.",
        "Speaking with her mouth full, pointing at me with the fries in her hand.",
        "..",
        "What an earnest smile she has on right now.",
        ".",
        ".",
        "{player}: \"..You have something on your face.\"",
        "{girl}: \"Whamft? whermm?\"",
        "She responds with her mouth filled to the brim.",
        "I take a napkin and wipe the corner of her mouth.",
        "{player}: \"Right here, be careful not to spill any on your clothes.\"",
        "Taking a bite of my burger, a torrent of emotion washes over me.",
        "Damn.",
        "I could probably eat three or four of these."
    }
end
