TrueEnd = Story:extend()

function TrueEnd:new()
    TrueEnd.super.new(self)
    self.lines = { 
		"#bg gfx/bg1.png",
		"EPILOGUE",
		"#bg gfx/bg6.png",
		"1 Week later...",
		"#bg gfx/bg7.png",
		"I'm still cleaning out the remnants of {girl}'s room.",
		"..",
		"I didn't have the heart in me to finish it in one sitting.",
		"Once it was all cleaned out, then that would truly be the end of it.",
		"Our planet is still here so...",
		"I can only assume we passed the test.",
		"(Rustle)",
		"(Rustle)",
		"A metallic shimmer glimmers against the light coming through the window.",
		"Hm..?",
		"Is this...the device she left?",
		"I set the packing boxes aside.",
		"This looks like...",
		"A regular smartphone.",
		"I attempt to use the buttons on the side of it--",
		"--it easily unlocks the screen.",
		"The last used application restores itself to the screen.",
		"..",
		"An inbox?",
		"INBOX(0)",
		"SENT(3)",
		"DRAFT(1)",
		"I press the SENT category.",
		"SENT(3)",
		"SUBJECT: !!!!! ATTN: A.C.P.P. COMPULSORY PARTICIPATION !!!!!",
		"SUBJECT: !!!!! WE ARE WATCHING YOU TAKER !!!!!",
		"SUBJECT: !!!!! ATTN: A.C.P.P. STATUS UPDATE !!!!!",
		"...",
		"...What?",
		"...!!!!...",
		"...????...",
		"Confused, I look for answers in the DRAFT category.",
		"DRAFT(1)",
		"SUBJECT: ...Sorry, {player}",
		"My handles tremble a bit out of nervousness as I press to read the draft.",
		"SUBJECT: ...Sorry, {player}",
		"BODY:",
		"Sorry, {player}.",
		"There's... no easy way to say this.",
		"There..",
		"There is no Outer Federation.",
		"I never had parents.",
		"My grandparents took me in as their own and raised me in their stead.",
		"But... they were ousted from their \"position\" 13 years ago",
		"They returned to the masses of society without issue and passed, leaving me behind.",
		"I...I saw you.",
		"How gentle you were in the districts, taking care of the abandoned units.",
		"I thought that maybe.",
		"Maybe I could find a way to be of use to you, so that you might take me in!",
		"But...I couldn't find a way.",
		"...",
		"..I'm sorry for forcing myself into your life...",
		"I put an unforgiveable burden on you without your consent.",
		"I was a child then but you raised me to be better.",
		"I know now what I did was wrong.",
		"I want to make--",
		"*KNOCK KNOCK*",
		"A noise behind me interrupts my reading.",
		"I turn around--",
		"#portrait gfx/portrait_end_researcher.png",
		"!!",
		"{girl}: \"Ahhh...looks like I've been found out.\"",
		"She has a sly grin on her face.",
		"{player}: \"...I thought I'd never see you again.\"",
		"She twirls in place with her hands showing off her uniform.",
		"..That's..my research facility's uniform.",
		"{girl}: \"It took some time to get this..but I wanted to surprise you and come clean.\"",
		"{girl}: \"Well.. what do you think.\"",
		"Her face beams so brightly, I think I might melt.",
		"The brightness seems to be overloading my eyes.",
		"Yeah that makes sense.",
		"They're increasing in fluid production to keep from drying out.",
		"{girl}: \"I'll take your silence as a compliment.\"",
		"{girl} walks over to me and embraces me.",
		"{girl}: \"Thanks for everything.\"",
		"{girl}: \"...But you'll have to take care of me for a little bit longer.\"",
		"{girl}: \"...Father.\"",
		"#bg gfx/bg6.png",
		"Ah.",
		"So this is \"it\".",
		"#bg gfx/bg1.png",
		"TRUE END."
    }
end
