CityIntroStory = Story:extend()

function CityIntroStory:new()
    CityIntroStory.super.new(self)
    self.lines = { 
        "#bg gfx/bg1.png",
        "3014.UC CAPITAL DISTRICT",
        "04.01 1800",
        "#bg gfx/bg5.png",
        "#music bgm/Lazy Marine - 91 T1.wav",
        "It's been a couple months now, taking care of {girl}.",
        "#portrait gfx/portrait_baby_{type}.png",
        "I've taken her out to walk in the city a couple times with the hope of getting her familiar with our planet but only through the Capital District.",
        "The Capital District housed the highest performers of society and it only made sense to take her there if I was to give her the best",
        "impression of humans.",
        "Surprisingly, it was tough for her at first, the waves of unfamiliar people, pushing without care to reach their destination.",
        "But, she's quick to pick things up.",
        "Looking ahead, I can see her deftly avoiding the touch of other people in a crowd--a skill often overlooked.",
        "She was snaking through them like they were obstacles in a maze.",
        "Her face scrunched deep with concentration but she seemed.. to be having fun?",
        "To be honest, if I hadn't been told what she really was I would've mistaken her for any other child.",
        "But this child carries a heavy burden--I know that.",
        "Truth be told, children in this part of the city and where I live are seldom seen.",
        "They end up getting shipped off to specialized dormitories to mold them to fit society properly.",
        "Their contribution IS all that mattered after all.",
        "Many would not see their biological parents for decades--not that the parents minded.",
        "It was a matter of fact that caring for someone else could only hold back their true potential.",
        "..But..",
        "Seeing her like this, ignorant to the world and its unwritten rules, welled me up with a strange feeling.",
        "Maybe it's because I haven't really seen any kids around here in years.",
        "..Are all GIVERs like this?",
        "{girl}: \"TAKER.\"",
        "We pause in the middle of the sidewalk.",
        "{player}: ..?",
        "{girl}: ...",
        "She's staring at an emblem engraved into the side of a store selling ice-cream.",
        "#music bgm/Lazy Marine - 91 T2.wav",
        "{girl}: ...",
        "{player}: \"Oh, that?\"",
        "{player}: \"That's the former Royal Crest.\"",
        "Looking around, I realize I had been so distracted by the GIVERs movements that we stumbled out of the Capital District and into the",
        "Auxiliary District.",
        "The people that live here have been deemed sub-optimal by the government and it shows in its architecture.",
        "Much less care is given to the machinery here and it's not uncommon to find filth in the streets.",
        "This ice-cream shop must be a royal sympathizer, judging by the crest.",
        "When the Royal Family and Parliament were ousted by the neo-government, there was a large opposition to the new societal classifications.",
        "Things seemed to be better for these people under the old system--I can tell you now the current system sure as hell is doing them no",
        "favors.",
        "{player}: We can't stay here for too long.",
        "{girl}: ...",
        "{player}: \"..Do you want some ice-cream?\"",
        "{girl}: !..",
        "Her eyes beamed with curiosity, I'm sure she's never had one of these before.",
        "Buying two cones, I guide her over to a nearby bench so we can enjoy our quick snack.",
        "She sits on one end of the bench, hastily awaiting me to hand her the frozen treat.",
        "I hand it to her, my hands lightly brushing against hers for a brief moment.",
        "Warm.",
        "I guess these aliens are warm blooded too.",
        "I take my seat at the other end of the bench to enjoy my portion as well.",
        "Looking over at {girl}, her brow furrows and I spot a slight frown on her mouth.",
        "She quickly rises to a stand, cheeks puffed.",
        "{player}: !..",
        "And takes a handful of graceful strides towards me.",
        "She sharply turns her body and takes a seat... right next to me.",
        "{player}: ..",
        "{girl}: ...",
        "We finish our ice-cream together in silence."
		,"#music bgm/Lazy Marine - 91 full.wav"
    }
end
