HelpPt2Story = Story:extend()

function HelpPt2Story:new()
    HelpPt2Story.super.new(self)
    self.lines = {
        "#bg gfx/bg1.png",
        "3018.UC",
        "12.25 1745 HOME",
        "#music bgm/Lazy Marine - 91 T2.wav",
        "#bg gfx/bg7.png",
        "..",
        "...",
        "Nnnh..",
        "My eyes slowly open as they accustom to the low lighting of the room.",
        "..",
        "This ceiling.",
        "I recognize this ceiling.",
        "This is the same ceiling I look at every morning.",
        "Then...",
        "I'm..in my bed?",
        "Gradually sitting up, I feel something wet drop from my head.",
        "It seems to be..a wet towel?",
        "I unravel the folded towel in my hands.",
        "Judging by the temperature, it's still cool.",
        "This must have been freshly applied...",
        "I wipe my face with the towel, hoping the water cooled against my skin would help me find my bearings.",
        "To the side of the bed sits an empty stool.",
        "To my right, on the nightstand, I spot some pill bottles and an empty bowl.",
        "A rhythmic thumping startles me.",
        "In the distance, I can hear footsteps...",
        "..but the cadence is uneven..",
        "..",
        "..two people?",
        "Just as I begin to wonder who could be in my house, the door creaks open--",
        "#portrait gfx/portrait_baby_{type}.png",
        "Oh yeah.",
        "{girl} lives here too now.",
        "{girl} stands in the doorway, mouth slightly agape.",
        "A sweet and crisp aroma fills the room.",
        "In her hands is a bowl of freshly cut apples.",
        "..but not for long.",
        "The bowl falls to the floor as she lets go of it, spilling the contents out across the floor.",
        "There are tears in her eyes as she rushes over to me, arms stretched out.",
        "My waist constricts from her embrace.",
        "Her tears drench the sheets--",
        "{girl}: \"I-I'm..(hic)..so glad, you're.. finally awake!!\"",
        "Her words are hard to make out--they come out stuttered and stifled by the bedsheets in her face.",
        "{player}: \"Oh..haha..sorry to make you worry..\"",
        "I place my hand on her head to comfort her as my attention is drawn towards the other figure in the doorway.",
        "A white-coated man steps into the doorway.",
        "His face exudes an gentle aura, even with his apparent old-age.",
        "Comforting, like a grandparent you could always count on.",
        "..but, I didn't recognize this man.",
        "White-coated Man: \"Glad to see you've made a full recovery.\"",
        "{player}: \"..Me too..\"",
        "{player}: \"..Sorry, but.. who are you again?\"",
        "White-coated Man: \"Oh, I'm no one. Just returning a favor.\"",
        "The White-coated Man gives me a sly wink as he kneels to pick up the fallen apple slices.",
        "White-coated Man: \"..Thank you for helping my daughter out.\"",
        "..",
        "Oh..",
        "He must mean when we went to the Auxiliary District and ran into that Capital District couple..",
        "White-coated Man: \"You should be thankful to have such a wonderful daughter.\"",
        "{girl}'s crying seems to stop.",
        "I feel the place where her face is buried slightly increase in temperature.",
        "..Her ears are red.",
        "White-coated Man: \"When you collapsed, she immediately ran out to the Auxiliary District asking desperately for help.\"",
        "White-coated Man: \"She was so distraught I thought that you were in much worse condition than you actually were.\"",
        "White-coated Man: \"Nonetheless, I prescribed her a course of pills for her to give to you and she's been bringing me here for a daily checkup.\"",
        "White-coated Man: \"She stayed by your side every day it seems--I gave her some of our apples to peel for you as well to help you get",
        " the nutrition you needed.\"",
        "{girl} releases her grip from me and begins to stand.",
        "She wipes the remnant tears from her eyes but keeps her hands there covering her face.",
        "..Her ears are still red.",
        "White-coated Man: \"..Be careful, next time.\"",
        "White-coated Man: \"You wouldn't want to make your daughter worry any more.\"",
        "The White-coated Man walks over and hands her the bowl she dropped.",
        "{girl}: \"I..I-I'll go cut some more!\"",
        "The White-coated Man smiles even bigger as she briskly escapes the room, bowl in hand.",
        "White-coated Man: ...",
        "{player}: ...",
        "#bg gfx/bg6.png",
        "White-coated Man: \"Daughters sure are something, aren't they?\"",
        "{player}: ...Yeah."
    }
end
