GoodbyeStory = Story:extend()

function GoodbyeStory:new()
    GoodbyeStory.super.new(self)
    self.lines = { 
        "#bg gfx/bg1.png",
        "3019.UC",
        "12.31 2200 HOME",
        "#music bgm/Lazy Marine - 91 T1.wav",
        "#bg gfx/bg7.png",
        "Last day.",
        "I can only hope that I raised her correctly.",
        "The Outer Federation decides the fate of our whole planet..",
        "..If I did a bad job then--",
        "--No.",
        "What's done is done.",
        "I did the best I could.",
        "As I sit at my desk, I feel a gaze trace the back of my head.",
        "#portrait gfx/portrait_baby_{type}.png",
        "{girl} is in my doorway again.",
        "{player}: \"..Oh..hey.\"",
        "{player}: \"Something wrong?\"",
        "{girl}: \"No..\"",
        "{player}: \"..Today's the last day, huh?\"",
        "{girl}: ..",
        "{girl}: (nods)",
        "{player}: \"These past six years have gone by so fast...\"",
        "{player}: \"..but honestly, I'm not sure what else I have left to give you.\"",
        "I get up from my chair and push it underneath the desk.",
        "{player}: \"Hey..it's getting late. We should head to bed.\"",
        "I turn towards my bed and make a stride towards it.",
        "..",
        "An opposite force seems to stop me though.",
        "{girl} grips the cuff of my clothing, a pained expression painting her face.",
        "{player}: ...",
        "{player}: \"Want to sleep together? One last time?\"",
        "She nods fervently.",
        "..",
        "We slip into bed, content.",
        "{girl}: ...",
        "{girl}: \"Good night..father.\"",
        "{player}: ...",
        "{player}: \"Good night, {girl}.\"",
        "..",
        "...",
        "I slept that night, clear of mind.",
        "As if the day of judgement was never coming.",
        "#bg gfx/bg1.png",
        "..",
        "...",
        "....",
        "#bg gfx/bg6.png",
        "When I awoke, she was gone.",
        "DAYS REMAINING: 0"
    }
end
