MidwayCheckupStory = Story:extend()

function MidwayCheckupStory:new()
    MidwayCheckupStory.super.new(self)
    self.lines = { 
        "3016.UC",
        "12.31 1200",
        "It's around noon and {girl} happened to be around to eat lunch. ",
        "I've made sure to cut some apples up on the side too since she's been taking a liking to them in particular lately.",
        "{player}: \"{girl}? Lunch is ready!\"",
        "..",
        "No response.",
        "Maybe she can't hear me from her room?",
        "I turn off the kitchen stove and wipe my hands.",
        "I make my way to her room and give the door a few knocks.",
        "{player}: \"Hello? {girl}? You in there? The food's ready..\"",
        "..",
        "No response.",
        "Well, I have no choice I suppose.",
        "I make sure to make as much noise grabbing the knob to alert her that I'm coming in.",
        "As the door swings open, I see her sitting at her desk with a device in her hand.",
        "{girl}: !!",
        "Great, seems she's noticed me now.",
        "Her hands fumble around as she attempts to conceal the device.",
        "Federation technology?",
        "Not sure..couldn't get a good look.",
        "But if the Outer Federation is watching me even now, I should probably pretend like I didn't see anything.",
        "{player}: \"Just wanted to let you know that lunch was ready.\"",
        "{girl}: \"..Okay..\"",
        "*BEEP*",
        "What?",
        "*BEEP*",
        "From my room?",
        "*BEEP*",
        "Oh no...",
        "I rush back to my room to check my e-mail.",
        "Sure enough..",
        "SUBJECT: !!!!! ATTN: A.C.P.P. STATUS UPDATE !!!!!",
        "FROM: <REDACTED BY USER>",
        "BODY: ",
        "TO CARETAKER,",
        "WE HAVE BEEN OBSERVING YOU.",
        "YOU HAVE MADE FOR A SUITABLE CARETAKER THUS FAR.",
        "HEALTH STATUS OF UNIT:",
        "[ 011-TMXEPMZI ]",
        ".ALL SYSTEMS NOMINAL",
        "BASED ON REPORTS RECEIVED FROM G.I.V.E.R. UNIT",
        "[ 011-TMXEPMZI ]",
        "WE HAVE SEEN A MARKED INCREASE IN CHEMICAL ACTIVITY UPON RECEIVING:",
        "[ APPLE ]",
        "IT IS RECOMMENDED TO CONTINUE ADMNISTERING",
        "[ APPLE ]",
        "SIGNED,",
        "OUTER FEDERATION",
        "DAYS REMAINING: 1095",
        "..",
        "...",
        "Good thing I cut those apples."
    }
end
