FirstContactStory = Story:extend()

function FirstContactStory:new()
    FirstContactStory.super.new(self)
    self.lines = { 
        "30XX.UC 06.20 HOME",
		"…",
		"..Nnh..",
		"A feel a light creep slowly up my face, the burn from its warmth prickling my skin.",
		"What time is it?",
		"1500.",
		"..already past noon.",
		"I must’ve really overdone it last night analyzing that memory unit..",
		"I haphazardly toss my sheets aside and muster the strength to start my day.",
		"Better now than neve-",
		"BEEP.",
		"BEEP.",
		"My computer monitor seems to be begging for some attention right now.",
		"..",
		"E-mail?",
		"When was the last time I got one of these?",
		"BANG BANG BANG",
		"The door?",
		"BANG BANG BANG",
		"That’s two unusual occurrences today...",
		"Sorry, computer but you’ll have to wait.",
		"BANG BANG BANG",
		"MC: \"Alright, alright! I’m coming!\"",
		"MC: \"Yes, can I he—\"",
		"My words cut short as I gaze upon…",
		"#portrait gfx/portrait_egg.png",
		"MC: \"..an egg?\"",
		"An egg-shaped, metallic enclosure dons the metal grating of my front doorstep. ",
		"Its shell whirrs with the hum of hydraulics pumping, slowly peeling apart the layers of the enclosure. A slightly burnt smell wafts over me as the hydraulic system discharges a dense white smoke that lingers at my feet. ",
		"A hatch-like mechanism slowly lifts itself and inside is..",
		"A girl?",
		"But she looks… different?",
		"Her silhouette becomes clearer and clearer as the smoke disperses.",
		"She’s sleeping…",
		"I look around for any signs of how this.. \"thing\" got here.",
		"A long trail of scratch marks on the grating trace the journey of this egg to my doorstep.",
		"Whoever wanted this here, made no mistake—this was meant for me.",
		"Well…it’s a good thing I have no neighbors… being Head of R&D for the neo-government, placed in my own private housing does come with some perks,  I suppose. ",
		"I turn my attention back to the sleeping visage of the girl inside.",
		"Who knows what someone might think if they saw this.",
		"My praises of good fortune are quickly cut short, however, as the girl inside opens her eyes and turns her attention towards me.",
		"Girl: \"..TAKER..\"",
		"MC: \"Excuse me?\"",
		"Her stare locks onto my eyes, running a chill down my spine as she emerges from her egg-shaped cocoon.",
		"	Girl: \"TAKER.\"",
		"Her right arm raises and points past me.",
		"An ominous silence fills the air, constricting my chest.",
		"Has this girl blinked yet?",
		"Turning around, I see she’s pointing directly at my computer.",
		"She gracefully drops her arm, grasping her other hand behind her back.",
		"Is she fidgeting? Is she anxious about something?",
		"Not sure what to make of this situation, I can only assume this is related to that mail...",

		"SUBJECT: !!!!! ATTN: A.C.P.P. COMPULSORY PARTICIPATION !!!!!",
		"FROM: <REDACTED BY USER>",
		"BODY: ",
		"TO CARETAKER,",
		"YOU’VE BEEN CHOSEN TO PARTICIPATE IN THE ADVANCED CIVILIZATION PRUNING PROGRAM, HERE ON REFERRED TO AS THE ACPP. ",
		"THE OUTER FEDERATION HAS DEEMED YOUR PLANET TO MEET THE CRITERIA FOR ",
		"[ CIV-ii CLASS A.0 ]  ",
		"DESIGNATION. ",
		"AS SUCH, YOU HAVE BEEN APPOINTED CARETAKER FOR \"GIRLISH INSIGHT AND VALUATION FOR EXTERMINATION RECONNAISSANCE\" UNIT:",
		"[ 011-TMXEPMZI ]",
		"AS CARETAKER TO G.I.V.E.R. UNIT, YOU ARE REQUIRED TO REAR THE UNIT FOR ",
		"NUMERATION SYSTEM: [ 6 ]",
		"LOCAL UNIT: [ YEARS ]",
		"AFTER REARING PERIOD HAS COMPLETED, THE FEDERATION WILL COLLATE THE DATA AND PERFORMANCE OF G.I.V.E.R. UNIT ",
		"[ 011-TMXEPMZI ] ",
		"TO DETERMINE WHETHER YOUR PLANET MAY ASCEND TO ",
		"[ CIV-ii CLASS A.0 ]",
		"FAILURE TO SUCCESSFULLY COMPLETE THIS PROGRAM OR UNSATISFACTORY PERFORMANCE AFTER THE REARING PERIOD WILL RESULT",
		"IN",
		"COMPLETE",
		"AND",
		"TOTAL",
		"DESTRUCTION",
		"OF",
		"YOUR",
		"PLANET.",
		"WE ARE WATCHING YOU TAKER.",
		"SIGNED,",
		"OUTER FEDERATION",
		"DAYS REMAINING: 2190",
		".",
		"..",
		"...!!!...",
		"..is this a joke..",
		"..even after all our technological advancement we’ve never been contacted any \"Outer Federation\".",
		"Hell, we still haven't even confirmed the existence of ANY aliens to date.",
		"I look back at the figure in my doorway-- the girl still seems to be fidgeting with her hands behind her back.",
		"..is that the GIVER?",
		"BEEP.",
		"BEEP.",
		"Again??",
		"SUBJECT: !!!!! WE ARE WATCHING YOU TAKER !!!!!",
		"FROM: <REDACTED BY USER>",
		"BODY: <EMPTY>　",
		"..",
		"…",
		"MC: ..",
		"Girl: ..",
		"MC: ..you hungry?",
		"The girl stops fidgeting, ",
    }
end
